version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_USER=postgres
          - POSTGRES_DB=simple_blog_api
          - POSTGRES_TYPE=postgres
          - POSTGRES_HOST=postgres
        volumes:
          - ./localDataCenter:./data
        command: ["postgres", "--save", "1 1"] 
   
    node-app:
        depends_on:
          - postgres
        restart: always
        image : docker.io/snehasharma2606/simpleblogapi:1.2
        # build:
        #  context: ./
        ports:
           - "3000:3000"
        environment:
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=simple_blog_api
            - PGPASSWORD=postgres_password
            - PGPORT=5432